### ISSUE TITLE
Multiple Directive Resource Contention

### ISSUE THREAD

**Issue by dustymiller** [softmonkeyjapan/angular-google-picker#12] opened 2015-06-15 19:06 UTC
The lk-google-picker directive causes an error when added to an HTML element with another directive that is creating an isolate scope.  (See https://docs.angularjs.org/error/$compile/multidir).  Using the directive on an <a>  that also contains tooltip directives from the angular-ui project.  HTML source code is:

```html
<a class="list-group-item" id="mnuGooglePicker" lk-google-picker after-select="afterSelectCallback" ng-disabled="isUploading" ng-show="!pageIsReadOnly" tooltip="Get Images from Google Drive" tooltip-popup-delay="750" tooltip-placement="right" tooltip-append-to-body="true">
    <i class="fa fa-fw fa-google"></i>&nbsp;Google Drive
</a>
```

Is it possible to use this directive in conjunction with other directives that may be creating their own isolate scope?

**Comment by softmonkeyjapan** [comment] 2015-06-25 04:57
I've tried adding a tooltip to the element as shown in your snippet but I cannot reproduce the error. It works fine on my end. Could you setup a plunkr with your code so I can debug it?

Thanks

**Comment by softmonkeyjapan** [comment] 2015-09-18 00:41
Closing it for now. Please, feel free to comment if you need.

**Closed by softmonkeyjapan** 2015-09-18 00:41 UTC
